/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumCard: typeof import('./components/business/AlbumCard.vue')['default']
    AppButton: typeof import('./components/common/AppButton.vue')['default']
    AppCard: typeof import('./components/common/AppCard.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppNavbar: typeof import('./components/layout/AppNavbar.vue')['default']
    AppTag: typeof import('./components/common/AppTag.vue')['default']
    ArticleCard: typeof import('./components/business/ArticleCard.vue')['default']
    BackTop: typeof import('./components/common/BackTop.vue')['default']
    ContactLinks: typeof import('./components/business/ContactLinks.vue')['default']
    DocToc: typeof import('./components/markdown/DocToc.vue')['default']
    ElImage: typeof import('element-plus/es')['ElImage']
    FallingLeaves: typeof import('./components/layout/FallingLeaves.vue')['default']
    HeroBanner: typeof import('./components/business/HeroBanner.vue')['default']
    ImageViewer: typeof import('./components/business/ImageViewer.vue')['default']
    LearningPath: typeof import('./components/business/LearningPath.vue')['default']
    MarkdownViewer: typeof import('./components/markdown/MarkdownViewer.vue')['default']
    MinecraftLever: typeof import('./components/layout/MinecraftLever.vue')['default']
    MinecraftVines: typeof import('./components/layout/MinecraftVines.vue')['default']
    Pagination: typeof import('./components/common/Pagination.vue')['default']
    ProjectCard: typeof import('./components/business/ProjectCard.vue')['default']
    ReadingProgress: typeof import('./components/common/ReadingProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/common/SearchBar.vue')['default']
    SkillTree: typeof import('./components/business/SkillTree.vue')['default']
    TagSelect: typeof import('./components/admin/TagSelect.vue')['default']
    ThemeSwitch: typeof import('./components/common/ThemeSwitch.vue')['default']
    Timeline: typeof import('./components/business/Timeline.vue')['default']
    WaterfallItem: typeof import('./components/business/WaterfallItem.vue')['default']
  }
}
